config/routes.rb
Rails.application.routes.draw do
  resources :rooms, only: [:show, :create] do
    member do
      post :entries, :messages
    end
  end
  get 'profiles/new'
  get 'sessions/new'
  root 'pages#index'
  
  resources :users
  resources :profiles
  
  resources :messages
  resources :entries
  resources :purchases
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  put 'users/follow/:user_id' => 'users#follow'
  get 'users/follow_list/:user_id' => 'users#follow_list'
  get 'users/follower_list/:user_id' => 'users#follower_list'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  after_destroy :destroy_empty_room
  belongs_to :user
  belongs_to :room
  
  private
    
    def destroy_empty_room
      room.destroy if room.reload.entries.empty?
    end
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  belongs_to :follower,   polymorphic: true
  belongs_to :followable, polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  validates :room_id, presence: true
  validates :user_id, presence: true
  validates :content, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :introduction, presence: true
  validates :image, presence: true
  validates :age, presence: true
  validates :nickname, presence: true
  validates :price, presence: true
  enum sex: { man: 0, woman: 1}
  belongs_to :user
  has_many :purchases
  has_many :purchase_users, through: :purchases, source: 'user'
  mount_uploader :image, ImageUploader
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :profile
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :members, class_name: "User", through: :entries, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  RULE =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, format: {with: RULE}
  validates :password, length: { in: 8..32 }, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
  validates :password_confirmation, length: { in: 8..32 }
 
  has_secure_password
  has_one :profile
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, class_name: "Room", through: :entries
  has_many :purchases
  has_many :purchase_profiles, through: :purchases, source: 'profile'
  enum sex: { man: 0, woman: 1}
  
  acts_as_followable
  acts_as_follower
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  #before_action :logged_in?
  before_action :correct_user, only: :destroy
  
  def create
    @room = Room.find(params[:room_id])
    params[:user_id].each do |guest_user|
      if @room.member?(user_id)
        
      else
        @room.add_member(user_id)
      end
    end
  end

  def destroy
    @entries.destroy
    flash[:success] = "トークルームから退出しました"
    redirect_to root_path
  end
  
  private
    
    def correct_user
      @entries = current_user.entries.find_by(id: params[:id])
      redirect_to root_path if @entries.nil?
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :logged_in?
  before_action :correct_user,   only: :destroy
  
  def destroy
    @room = @message.room
    @message.destroy
    flash[:success] = "メッセージが削除されました"
    redirect_to @room
  end
  
  def create
    #binding.pry
    @message = Message.new(message_params)
    room = Room.find(message_params[:room_id].to_i)
    #binding.pry
    if @message.save
      redirect_to messages_path(room_id: room.id), method: :get
    else
      @messages = room.messages
      redirect_to root_path
    end
  end
  
  def index
    # binding.pry
    @messages = Message.where(room_id: params[:room_id])
  end
    
  private
    
    def message_params
      #params[:message].merge!({ user_id: current_user.id, room_id: @room.id })
      params.require(:message).permit(:user_id, :room_id, :content).merge(user_id: current_user.id)
    end
  
    def correct_user
      @message = current_user.messages.find_by(id: params[:id])
      redirect_to root_path if @message.nil?
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if logged_in?
      @profile = Profile.where(user_id: current_user.id)
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @profile = Profile.find_by(user_id: current_user.id)
    @profiles = Profile.where.not(user_id: current_user.id, sex: @profile.sex).includes(:purchase_users)
  end
  
  def new
    @profile = Profile.new
  end
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    if @profile.save
      redirect_to profiles_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end
  
  def edit
    @profile = Profile.find_by(user_id: current_user.id)
  end
  
  def update
    @profile = Profile.find_by(user_id: current_user.id)
    if @profile.update_attributes(profile_params)
      redirect_to "/", success: 'プロフィールを更新しました'
    else
      flash.now[:danger] = "更新に失敗しました"
      render action: :edit
    end
    
  end
  
  def destroy
    @profile = Profile.find_by(user_id: current_user.id)
    @profile.destroy
    redirect_to root_path, success: 'プロフィールを削除しました'
  end

  private
  def profile_params
    params.require(:profile).permit(:image, :introduction, :age, :price, :nickname, :sex)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  #before_action :logged_in_user
  #before_action :correct_member, only: [:show, :messages]
  
  def show
    @room = current_user.rooms.find(params[:id])
    @messages = @room.messages
    @message = Message.new
    #binding.pry
  end
  
  
  private
    
    def message_params
      params[:message].merge!({ user_id: current_user.id, room_id: @room.id })
      params.require(:message).permit(:user_id, :room_id, :content)
    end
    
    def correct_member
      @room = current_user.rooms.find_by(followable_id: params[:id])
      redirect_to root_path if @room.nil?
    end
    
    def correct_user
      @message = current_user.messages.find_by(id: params[:id])
      redirect_to root_path if @message.nil?
    end
    
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to root_path
      end
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end

  def follow
    @user = User.find(params[:user_id])
    current_user.follow(@user)
    
    @room = Room.new
    @room.user_id = current_user.id
    @room.follower_id = current_user.id
    @room.followable_id = params[:user_id]
    @room.save
    
    @entry = Entry.new
    @entry.room_id = @room.id
    @entry.user_id = current_user.id
    @entry.save
    
    @entry = Entry.new
    @entry.room_id = @room.id
    @entry.user_id = params[:user_id]
    @entry.save
    
    redirect_to room_path(@room.followable_id)
  end
  
  def follow_list
    @user = User.find(params[:user_id])
  end
  
  def follower_list
    @user = User.find(params[:user_id])
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/messages/_message.html.erb
<li id="message-<%= message.id %>">
  <% user = message.user %>
  <div class="balloon">
    <% unless current_user?(user) %>
      <div class="user"><%= link_to user.name, user %></div>
    <% end %>
    <div class="content"><%= message.content %></div>
    <div class="timestamp">
      Posted <%= time_ago_in_words(message.created_at) %> ago.
      <% if current_user?(user) %>
        <%= link_to "delete", message_path(message), class: "delete", method: :delete %>
      <% end %>
    </div>
  </div>
</li>

app/views/messages/index.html.erb
<div class="message-index-wrapper">
  <div class="content">
    <%= @messages.each do |message| %>
      <%= message.content %>
    <% end %>
  </div>
</div>

  
  
  
 

app/views/profiles/edit.html.erb
<div class="profile-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">プロフィールを更新しよう!</h1>
        <%= form_for @profile do |f| %>
          <div class="form-group">
            <%= f.label :nickname %>
            <%= f.text_area :nickname, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image%>
          </div>
          
          <div class="form-group">
            <%= f.label :Sex, class: 'text-white' %><br />
            <%= f.label :man, class: 'text-white'  %>
            <%= f.radio_button :sex, :man %>
            <%= f.label :woman, class: 'text-white'  %>
            <%= f.radio_button :sex, :woman %>
          </div>
          
          <div class="form-group">
            <%= f.label :introduction %>
            <%= f.text_area :introduction, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :price %>
            <%= f.text_area :price, class: 'form-control' %>
          </div>
　　　　　<% if logged_in? %>
            <%= f.submit '更新', class: 'btn btn-black btn-block' %>
          <% end %>
          <%= link_to "削除", profile_path(@profile), method: :delete %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/index.html.erb
<div class="profile-index-wrapper">
  <div class="container">
    <% @profiles.each do |profile| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="profile-index-single">
            <h2 class="prifile-author">
              <%= profile.nickname %>
            </h2>
            <%= image_tag profile.image.url %>
            
            <% if !current_user.following? profile.user %>
              <%= link_to "BUY", {controller: :users, action: :follow, user_id: profile.user.id}, method: :put %>
            <% end %>
            
            <p class="profile-text">
              <%= profile.introduction %>
              <%= profile.age %>
              <%= profile.price %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="profile-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Let's make your PROFILE!!</h1>
        <%= form_for @profile do |f| %>
          <div class="form-group">
            <%= f.label :nickname %>
            <%= f.text_area :nickname, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image%>
          </div>
          
          <div class="form-group">
            <%= f.label :Sex, class: 'text-white' %><br />
            <%= f.label :man, class: 'text-white'  %>
            <%= f.radio_button :sex, :man %>
            <%= f.label :woman, class: 'text-white'  %>
            <%= f.radio_button :sex, :woman %>
          </div>
          
          <div class="form-group">
            <%= f.label :introduction %>
            <%= f.text_area :introduction, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :age %>
            <%= f.text_area :age, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :price %>
            <%= f.text_area :price, class: 'form-control' %>
          </div>
　　　　　<% if logged_in? %>
            <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">WELCOME TO TALKROOM!</h1>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <%= form_for @message,
                          html: { class: 'message-form'} do |f| %>
          <%= f.hidden_field :room_id, :value => @room.id %>
          <div class="field">
            <%= f.text_area :content, class: "content" %>
          </div>  
          <%= f.submit "Send", class: "btn btn-primary" %>
        <% end %>
        
      </div>
    </div>
  </div>
</div>

app/views/users/follow_list.html.erb
<div class="follower-list-wrapper" >
  <% @user.all_following.each do |user| %>
  <div class="follower_list">
    <%= user.name %> 
    <%= link_to "GO TO TALKROOM!", room_path(id: user.id) %>
  </div>  
  <% end %>
</div>  

 

app/views/users/follower_list.html.erb
<div class="follower-list-wrapper" >
  <% @user.followers.each do |user| %>
    <div class="follower_list">
      <%= user.name %>
      <%= link_to "GO TO TALKROOM!", room_path(id: user.id) %>
    </div>  
  <% end %>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign up</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
      </div>
    </div>
  </div>
</div>