config/routes.rb
Rails.application.routes.draw do
  resources :rooms, only: [:show, :create] do
    member do
      post :entries, :messages
    end
  end
  get 'profiles/new'
  get 'sessions/new'
  root 'pages#index'
  
  resources :users
  resources :profiles
  
  resources :messages
  resources :entries
  resources :purchases
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  put 'users/follow/:user_id' => 'users#follow'
  get 'users/follow_list/:user_id' => 'users#follow_list'
  get 'users/follower_list/:user_id' => 'users#follower_list'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  after_destroy :destroy_empty_room
  belongs_to :user
  belongs_to :room
  
  private
    
    def destroy_empty_room
      room.destroy if room.reload.entries.empty?
    end
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  belongs_to :follower,   polymorphic: true
  belongs_to :followable, polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  validates :room_id, presence: true
  validates :user_id, presence: true
  validates :content, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :introduction, presence: true
  validates :image, presence: true
  validates :age, presence: true
  validates :nickname, presence: true
  validates :price, presence: true
  enum sex: { man: 0, woman: 1}
  belongs_to :user
  has_many :purchases
  has_many :purchase_users, through: :purchases, source: 'user'
  mount_uploader :image, ImageUploader
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :profile
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :members, class_name: "User", through: :entries, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  RULE =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, format: {with: RULE}
  validates :password, length: { in: 8..32 }, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
  validates :password_confirmation, length: { in: 8..32 }
 
  has_secure_password
  has_one :profile
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, class_name: "Room", through: :entries
  has_many :purchases
  has_many :purchase_profiles, through: :purchases, source: 'profile'
  enum sex: { man: 0, woman: 1}
  
  acts_as_followable
  acts_as_follower
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if logged_in?
      @profile = Profile.where(user_id: current_user.id)
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  #before_action :logged_in_user
  #before_action :correct_member, only: [:show, :messages]
  
  def show
    @room = current_user.rooms.find(params[:id])
    @messages = @room.messages
    @message = Message.new
    #binding.pry
  end
  
  
  private
    
    def message_params
      params[:message].merge!({ user_id: current_user.id, room_id: @room.id })
      params.require(:message).permit(:user_id, :room_id, :content)
    end
    
    def correct_member
      @room = current_user.rooms.find_by(followable_id: params[:id])
      redirect_to root_path if @room.nil?
    end
    
    def correct_user
      @message = current_user.messages.find_by(id: params[:id])
      redirect_to root_path if @message.nil?
    end
    
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to root_path
      end
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end

  def follow
    @user = User.find(params[:user_id])
    current_user.follow(@user)
    
    @room = Room.new
    @room.user_id = current_user.id
    @room.follower_id = current_user.id
    @room.followable_id = params[:user_id]
    @room.save
    
    @entry = Entry.new
    @entry.room_id = @room.id
    @entry.user_id = current_user.id
    @entry.save
    
    @entry = Entry.new
    @entry.room_id = @room.id
    @entry.user_id = params[:user_id]
    @entry.save
    
    redirect_to room_path(@room.followable_id)
  end
  
  def follow_list
    @user = User.find(params[:user_id])
  end
  
  def follower_list
    @user = User.find(params[:user_id])
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Picks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
     <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to root_path do %>
          <span><%= image_tag "picks_logo.png", class: "navbar-brand" %></span>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%= link_to "あなたが購入した人のリスト", {controller: :users, action: :follow_list, user_id: current_user.id}, method: :get %>
            </li>
            
            <li>
              <%= link_to "あなたを購入した人のリスト", {controller: :users, action: :follower_list, user_id: current_user.id}, method: :get %>
            </li>
            
            <li>
              <%= link_to purchases_path, method: :get do %>
                <%= image_tag "icons/heart.png" %>
              <% end %>
            </li>
            <li>
              <% if @profile.blank? %>
                <%= link_to new_profile_path do %>
                  <%= image_tag "icons/profile.jpeg" %>
                <% end %>
              <% end %>
            </li>
            <li>
              <% if @profile.present? %>
                <%= link_to edit_profile_path(current_user.id) do %>
                  <%= image_tag "icons/edit.jpeg" %>
                <% end %>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= image_tag "icons/logout.png" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_path do %>
                <%= image_tag "icons/register.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= image_tag "icons/login.png" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    
    <%= yield %>
    <script>
    $(function(){
    $(".alert").fadeOut(5000);
    });
    </script>
  </body>
</html>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">WELCOME TO PICKS!</h1>
    <h2 class="text-white">Picks is a service that you can find Life partner.</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <% if logged_in? %>
          <%= %>
        <% else %>
          <%= link_to 'Sign up', new_user_path, class: 'btn btn-block btn-white' %>
        <% end %>
      </div>
      <div class="col-md-3">
        <% if logged_in? %>
          <%= %>
        <% else %>
          <%= link_to 'Log in', login_path, class: 'btn btn-block btn-white' %>
        <% end %>
      </div>
    </div>
  </div>
</div>